#!/bin/bash
# Migrate wiki content from global-workflow to wiki-automation

set -e

echo "==================================================================="
echo "Wiki Migration Tool"
echo "Migrate content from global-workflow wiki to wiki-automation wiki"
echo "==================================================================="
echo ""

# Check for WIKI_PAT
if [ -z "$WIKI_PAT" ]; then
    echo "⚠️  WIKI_PAT environment variable not set"
    echo ""
    echo "Please export your GitHub Personal Access Token:"
    echo "  export WIKI_PAT='your-token-here'"
    echo ""
    read -p "Press Enter to continue without authentication (public wikis only)..."
fi

# Set up git credentials if token provided
if [ -n "$WIKI_PAT" ]; then
    GIT_URL_PREFIX="https://x-access-token:${WIKI_PAT}@github.com"
else
    GIT_URL_PREFIX="https://github.com"
fi

echo "==================================================================="
echo "Step 1: Clone global-workflow wiki"
echo "==================================================================="

if [ -d "temp-global-workflow-wiki" ]; then
    echo "Removing existing temp-global-workflow-wiki..."
    rm -rf temp-global-workflow-wiki
fi

git clone ${GIT_URL_PREFIX}/AntonMFernando-NOAA/global-workflow.wiki.git temp-global-workflow-wiki || {
    echo "⚠️  Could not clone global-workflow wiki (may not exist or no access)"
    echo "Continuing without migration..."
    exit 0
}

cd temp-global-workflow-wiki

# Check if wiki has any content
if [ ! -f Home.md ] && [ "$(ls -A .)" = ".git" ]; then
    echo "✓ global-workflow wiki is empty, nothing to migrate"
    cd ..
    rm -rf temp-global-workflow-wiki
    exit 0
fi

echo "✓ Cloned global-workflow wiki"
echo ""
echo "Found pages:"
ls -1 *.md 2>/dev/null || echo "  (no markdown files)"
echo ""

cd ..

echo "==================================================================="
echo "Step 2: Clone wiki-automation wiki"
echo "==================================================================="

if [ -d "temp-wiki-automation-wiki" ]; then
    echo "Removing existing temp-wiki-automation-wiki..."
    rm -rf temp-wiki-automation-wiki
fi

git clone ${GIT_URL_PREFIX}/AntonMFernando-NOAA/wiki-automation.wiki.git temp-wiki-automation-wiki || {
    echo "⚠️  Could not clone wiki-automation wiki"
    echo "Make sure:"
    echo "  1. Repository exists: https://github.com/AntonMFernando-NOAA/wiki"
    echo "  2. Wiki is enabled in repository settings"
    echo "  3. Wiki has at least one page (create Home page)"
    echo ""
    rm -rf temp-global-workflow-wiki
    exit 1
}

cd temp-wiki-automation-wiki

# Initialize wiki if empty
if [ ! -f Home.md ]; then
    echo "# Wiki Automation" > Home.md
    echo "" >> Home.md
    echo "Daily activity summaries for all AntonMFernando-NOAA repositories." >> Home.md
    echo "" >> Home.md
    echo "See [[Daily Updates|Daily-Updates]] for automated summaries." >> Home.md
fi

echo "✓ Cloned wiki-automation wiki"
echo ""

cd ..

echo "==================================================================="
echo "Step 3: Migrate content"
echo "==================================================================="

# Copy pages from global-workflow wiki, excluding Daily-Updates (will be regenerated)
cd temp-global-workflow-wiki

for file in *.md; do
    if [ "$file" = "Daily-Updates.md" ]; then
        echo "⏩ Skipping Daily-Updates.md (will be auto-generated)"
        continue
    fi
    
    if [ -f "$file" ]; then
        echo "📄 Copying $file..."
        cp "$file" ../temp-wiki-automation-wiki/
    fi
done

cd ../temp-wiki-automation-wiki

echo "==================================================================="
echo "Step 4: Update references"
echo "==================================================================="

# Update any links that reference global-workflow wiki to wiki-automation wiki
for file in *.md; do
    if [ -f "$file" ]; then
        sed -i 's|global-workflow/wiki|wiki/wiki|g' "$file" 2>/dev/null || true
        sed -i 's|global-workflow\.wiki|wiki\.wiki|g' "$file" 2>/dev/null || true
    fi
done

echo "✓ Updated wiki links"

echo "==================================================================="
echo "Step 5: Commit and push"
echo "==================================================================="

git config user.name "wiki-migration"
git config user.email "noreply@github.com"

git add .
git status

if git diff --cached --quiet; then
    echo "✓ No changes to commit (content already up to date)"
else
    git commit -m "Migrate content from global-workflow wiki

Automated migration of wiki pages from global-workflow to wiki-automation.
Daily-Updates will be auto-generated by GitHub Actions."

    echo ""
    echo "Ready to push changes to wiki-automation wiki?"
    read -p "Press Enter to continue or Ctrl+C to abort..."
    
    git push
    echo "✓ Wiki content migrated successfully!"
fi

echo ""
echo "==================================================================="
echo "Step 6: Cleanup"
echo "==================================================================="

cd ..
rm -rf temp-global-workflow-wiki temp-wiki-automation-wiki

echo "✓ Temporary files cleaned up"
echo ""
echo "==================================================================="
echo "✅ Migration complete!"
echo "==================================================================="
echo ""
echo "Wiki accessible at:"
echo "  https://github.com/AntonMFernando-NOAA/wiki/wiki"
echo ""
echo "To remove global-workflow wiki (optional):"
echo "  1. Go to: https://github.com/AntonMFernando-NOAA/global-workflow/settings"
echo "  2. Scroll to 'Features'"
echo "  3. Uncheck 'Wikis'"
echo "  4. Confirm removal"
echo ""
echo "Note: This won't delete the wiki content immediately. GitHub keeps"
echo "deleted wikis for a grace period."
echo "==================================================================="
